openapi: 3.0.0
info:
  title: UMC Study API
  version: 1.0.0
  description: UMC Study API with express, API 설명
servers:
  - url: http://localhost:3000
paths:
  /review/add:
    post:
      tags:
        - Review
      summary: Add a new review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                product_id:
                  type: integer
                  example: 101
                rating:
                  type: integer
                  example: 5
                comment:
                  type: string
                  example: "Great product!"
              required:
                - user_id
                - product_id
                - rating
                - comment
      responses:
        '200':
          description: Review added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      reviewId:
                        type: integer
                        example: 1
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "COMMON001"
                  message:
                    type: string
                    example: "잘못된 요청입니다."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "COMMON000"
                  message:
                    type: string
                    example: "서버 에러, 관리자에게 문의 바랍니다."
