paths:
  /store/{storeId}/missions:
    get:
      tags:
        - Store
      summary: 특정 가게의 미션 목록 조회
      parameters:
        - name: storeId
          in: path
          schema:
            type: integer
          required: true
          description: 가게 ID
        - name: missionId
          in: query
          required: false
          schema:
            type: integer
          description: 마지막으로 조회된 미션 ID (페이징을 위한 커서)
        - name: size
          in: query
          required: true
          schema:
            type: integer
          description: 한 번에 조회할 미션의 수
      responses:
        '200':
          description: 미션 목록 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                properties:
                  missionData:
                    type: array
                    items:
                      type: object
                      properties:
                        mission_id:
                          type: integer
                          example: 1
                        mission_name:
                          type: string
                          example: "미션 이름1"
                        description:
                          type: string
                          example: "미션 설명1"
                        reward:
                          type: string
                          example: "보상1"
                  cursorId:
                    type: integer
                    example: 1
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다

responses:
  BadRequest:
    description: 잘못된 요청
    schema:
      type: object
      properties:
        status:
          type: integer
          example: 400
        isSuccess:
          type: boolean
          example: false
        code:
          type: integer
          example: COMMON001
        message:
          type: string
          example: 잘못된 요청입니다

  ServerError:
    description: 서버 에러
    schema:
      type: object
      properties:
        status:
          type: integer
          example: 500
        isSuccess:
          type: boolean
          example: false
        code:
          type: integer
          example: COMMON000
        message:
          type: string
          example: 서버 에러, 관리자에게 문의 바랍니다
