paths:
  /user/signin:
    post:
      tags:
        - User
      summary: 회원가입
      parameters:
      - name: signIn
        in: body
        required: true
        schema:
          properties:
            email:
              type: string
              description: 유저 이메일
              example: swaggerTest@mail.com
            name:
              type: string
              description: 유저 이름
              example: swagger
            gender:
              type: string
              description: 유저 성별
              example: M
            birthYear:
              type: integer
              description: 생일 년도
              example: 2000
            birthMonth:
              type: integer
              description: 생일 월
              example: 1
            birthDay:
              type: integer
              description: 생일 일
              example: 31
            addr:
              type: string
              description: 주소
              example: swagger Test address
            specAddr:
              type: string
              description: 상세 주소
              example: swagger Test specAddr
            phone:
              type: string
              description: 전화 번호
              example: 010-0000-0000
            prefer:
              type: array
              description: 선호 카테고리 번호
              example: [1, 3, 5]
      responses:
        '200':
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "email": "swaggerTest@mail.com",
                  "name": "swagger",
                  "preferCategory": [
                    "한식",
                    "일식"
                  ]
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /user/{userId}/reviews:
    get:
      tags:
        - User
      summary: 내가 작성한 리뷰 목록
      parameters:
      - name: userId
        in: path
        required: true
        type: integer
        description: 유저 ID
      - name: reviewId
        in: query
        required: false
        type: integer
        description: 리뷰 ID 커서
      - name: size
        in: query
        required: false
        type: integer
        description: 가져올 리뷰 수
      responses:
        '200':
          description: 리뷰 목록 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                properties:
                  reviewData:
                    type: array
                    items:
                      type: object
                      properties:
                        store_name:
                          type: string
                          example: "가게 이름"
                        rate:
                          type: integer
                          example: 5
                        review_body:
                          type: string
                          example: "리뷰 내용"
                        create_date:
                          type: string
                          example: "2024.06.18"
                  cursorId:
                    type: integer
                    example: 123
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/responses/BadRequest'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/responses/ServerError'

  /user/{userId}/ongoing-missions:
    get:
      tags:
        - User
      summary: 내가 진행 중인 미션 목록
      parameters:
      - name: userId
        in: path
        required: true
        type: integer
        description: 유저 ID
      responses:
        '200':
          description: 진행 중인 미션 목록 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                properties:
                  missionData:
                    type: array
                    items:
                      type: object
                      properties:
                        mission_id:
                          type: integer
                          example: 1
                        mission_name:
                          type: string
                          example: "미션 이름"
                        description:
                          type: string
                          example: "미션 설명"
                        progress:
                          type: string
                          example: "진행 상태"
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/responses/BadRequest'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/responses/ServerError'

  /user/{userId}/ongoing-missions/{missionId}/complete:
    put:
      tags:
        - User
      summary: 진행 중인 미션 완료로 변경
      parameters:
      - name: userId
        in: path
        required: true
        type: integer
        description: 유저 ID
      - name: missionId
        in: path
        required: true
        type: integer
        description: 미션 ID
      responses:
        '200':
          description: 미션 완료 처리 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/responses/BadRequest'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/responses/ServerError'

responses:
  BadRequest:
    description: 잘못된 요청
    schema:
      type: object
      properties:
        status:
          type: integer
          example: 400
        isSuccess:
          type: boolean
          example: false
        code:
          type: integer
          example: COMMON001
        message:
          type: string
          example: 잘못된 요청입니다

  ServerError:
    description: 서버 에러
    schema:
      type: object
      properties:
        status:
          type: integer
          example: 500
        isSuccess:
          type: boolean
          example: false
        code:
          type: integer
          example: COMMON000
        message:
          type: string
          example: 서버 에러, 관리자에게 문의 바랍니다
